language: node_js
node_js:
  - "6"
os: x64
sudo: false
script:
  - npm run dist
env:
  - VER=0.0.1
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: dist/TANet Roamer 校園網路漫遊器 Setup ${VER}.exe
  skip_cleanup: true
  on:
    repo: ALiangLiang/TANetRoamer-desktop
    tags: true
    all_branches: true
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install npm -g
  - npm install electron-builder@next -g
  - npm install
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"