language: node_js
node_js:
  - "6"
os: x64
sudo: false
script:
  - npm run dist
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install npm -g
  - npm install electron-builder@next -g
  - npm install
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"