version: v0.0.{build}

skip_non_tags: true

environment:
  access_token:
    secure: 1tvNi1Tb8CC7s3rWEKQpdZj+OfLog51KdRAqX1QJ5RWC+7NY27vpSqbKRzM/TZOs

platform:
  - x64

artifacts:
  - path: "dist\\*.exe"
    name: release
  - path: "dist\\latest.yml"
    name: latest

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install npm -g
  - npm install electron-builder@next
  - npm install

build_script:
  - node --version
  - npm --version

test: off

before_deploy:
  - npm run release # build and rename exe file

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: "TANet-Roamer Setup {message}" # eg TANet-Roamer Setup xxxxxmessagexxxx
  provider: GitHub
  auth_token:
    secure: 1tvNi1Tb8CC7s3rWEKQpdZj+OfLog51KdRAqX1QJ5RWC+7NY27vpSqbKRzM/TZOs
  draft: false
  prerelease: false
  skip_cleanup: true
  on:
    appveyor_repo_tag: true
