version: v0.0.{build}

skip_non_tags: true

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install npm -g
  - npm install electron-builder@next
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

artifacts:
- path: "dist\\TANet Roamer 校園網路漫遊器 Setup 0.0.1.exe"
  name: release

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'TANetRoamer-desktop Setup'
  provider: GitHub
  auth_token:
    secure: 1tvNi1Tb8CC7s3rWEKQpdZj+OfLog51KdRAqX1QJ5RWC+7NY27vpSqbKRzM/TZOs
  artifact: "dist\\TANet Roamer 校園網路漫遊器 Setup 0.0.1.exe"
  draft: false
  prerelease: false
  skip_cleanup: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
    tags: true
