version: 0.0.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install npm -g
  - npm install electron-builder@next
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

branches:
  only:
    - master

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: b301eccf86416bae68fa5b2f31b0974c2eef9879
  artifact: /dist\\.*\.exe/
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
