version: v0.0.{build}

skip_non_tags: true

environment:
  access_token:
    secure: 1tvNi1Tb8CC7s3rWEKQpdZj+OfLog51KdRAqX1QJ5RWC+7NY27vpSqbKRzM/TZOs

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install npm -g
  - npm install electron-builder@next
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run release

test: off

artifacts:
- path: "dist\\*.exe"
  name: release
- path: "dist\\latest.yml"
  name: latest

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'TANetRoamer-desktop Setup'
  provider: GitHub
  auth_token:
    secure: 1tvNi1Tb8CC7s3rWEKQpdZj+OfLog51KdRAqX1QJ5RWC+7NY27vpSqbKRzM/TZOs
  draft: false
  prerelease: false
  skip_cleanup: true
  on:
    appveyor_repo_tag: true
